
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      C:\\Users\\ronca\\AppData\\Local\\Programs\\CLion\\bin\\mingw\\bin/ld.exe: cannot open output file a.exe: Invalid argument
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      1
      Assembler messages:
      Fatal error: can't create CMakeCCompilerId.o: Invalid argument
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -Aa 
      
      The output was:
      1
      <command-line>: error: missing '(' after predicate
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      1
      C:\\Users\\ronca\\AppData\\Local\\Programs\\CLion\\bin\\mingw\\bin/ld.exe: cannot open output file a.exe: Invalid argument
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      1
      gcc.exe: warning: '-mcpu=' is deprecated; use '-mtune=' or '-march=' instead
      gcc.exe: error: unrecognized command-line option '--target=arm-arm-none-eabi'
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      1
      Assembler messages:
      Fatal error: can't create CMakeCCompilerId.o: Invalid argument
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      C:\\Users\\ronca\\AppData\\Local\\Programs\\CLion\\bin\\mingw\\bin/ld.exe: cannot open output file a.exe: Invalid argument
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      1
      Assembler messages:
      Fatal error: can't create CMakeCCompilerId.o: Invalid argument
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -Aa 
      
      The output was:
      1
      <command-line>: error: missing '(' after predicate
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      1
      C:\\Users\\ronca\\AppData\\Local\\Programs\\CLion\\bin\\mingw\\bin/ld.exe: cannot open output file a.exe: Invalid argument
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      1
      gcc.exe: warning: '-mcpu=' is deprecated; use '-mtune=' or '-march=' instead
      gcc.exe: error: unrecognized command-line option '--target=arm-arm-none-eabi'
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      1
      Assembler messages:
      Fatal error: can't create CMakeCCompilerId.o: Invalid argument
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1117 (message)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
      gcc.exe: fatal error: no input files
      compilation terminated.
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1117 (message)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
      gcc.exe: fatal error: no input files
      compilation terminated.
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "//wsl.localhost/Ubuntu/home/maros/konecne/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-x2kgog"
      binary: "//wsl.localhost/Ubuntu/home/maros/konecne/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-x2kgog"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: ""
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '//wsl.localhost/Ubuntu/home/maros/konecne/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-x2kgog'
        
        Run Build Command(s): C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/mingw32-make.exe -f Makefile cmTC_c4f3d/fast
        C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_c4f3d.dir\\build.make CMakeFiles/cmTC_c4f3d.dir/build
        mingw32-make[1]: Entering directory '//wsl.localhost/Ubuntu/home/maros/konecne/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-x2kgog'
        Building C object CMakeFiles/cmTC_c4f3d.dir/CMakeCCompilerABI.c.obj
        C:\\Users\\ronca\\AppData\\Local\\Programs\\CLion\\bin\\mingw\\bin\\gcc.exe    -o CMakeFiles\\cmTC_c4f3d.dir\\CMakeCCompilerABI.c.obj -c C:\\Users\\ronca\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c
        Assembler messages:
        Fatal error: can't create CMakeFiles\\cmTC_c4f3d.dir\\CMakeCCompilerABI.c.obj: Invalid argument
        mingw32-make[1]: *** [CMakeFiles\\cmTC_c4f3d.dir\\build.make:77: CMakeFiles/cmTC_c4f3d.dir/CMakeCCompilerABI.c.obj] Error 1
        mingw32-make[1]: Leaving directory '//wsl.localhost/Ubuntu/home/maros/konecne/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-x2kgog'
        mingw32-make: *** [Makefile:126: cmTC_c4f3d/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Check for working C compiler: C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe"
    directories:
      source: "//wsl.localhost/Ubuntu/home/maros/konecne/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-6td6a9"
      binary: "//wsl.localhost/Ubuntu/home/maros/konecne/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-6td6a9"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: ""
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '//wsl.localhost/Ubuntu/home/maros/konecne/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-6td6a9'
        
        Run Build Command(s): C:/Users/ronca/AppData/Local/Programs/CLion/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/mingw32-make.exe -f Makefile cmTC_860b4/fast
        C:/Users/ronca/AppData/Local/Programs/CLion/bin/mingw/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_860b4.dir\\build.make CMakeFiles/cmTC_860b4.dir/build
        mingw32-make[1]: Entering directory '//wsl.localhost/Ubuntu/home/maros/konecne/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-6td6a9'
        Building C object CMakeFiles/cmTC_860b4.dir/testCCompiler.c.obj
        C:\\Users\\ronca\\AppData\\Local\\Programs\\CLion\\bin\\mingw\\bin\\gcc.exe    -o CMakeFiles\\cmTC_860b4.dir\\testCCompiler.c.obj -c "\\\\wsl.localhost\\Ubuntu\\home\\maros\\konecne\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-6td6a9\\testCCompiler.c"
        Assembler messages:
        Fatal error: can't create CMakeFiles\\cmTC_860b4.dir\\testCCompiler.c.obj: Invalid argument
        mingw32-make[1]: *** [CMakeFiles\\cmTC_860b4.dir\\build.make:77: CMakeFiles/cmTC_860b4.dir/testCCompiler.c.obj] Error 1
        mingw32-make[1]: Leaving directory '//wsl.localhost/Ubuntu/home/maros/konecne/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-6td6a9'
        mingw32-make: *** [Makefile:126: cmTC_860b4/fast] Error 2
        
      exitCode: 2
...
